/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const RawRecord = IDL.Record({
  'extracurriculars' : IDL.Nat,
  'studentName' : IDL.Text,
  'owner' : IDL.Principal,
  'predictedScore' : IDL.Nat,
  'predictedGrade' : IDL.Text,
  'studyHours' : IDL.Nat,
  'assignmentsCompleted' : IDL.Nat,
  'attendance' : IDL.Nat,
  'timestamp' : IDL.Int,
  'previousGPA' : IDL.Nat,
  'sleepHours' : IDL.Nat,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Stats = IDL.Record({
  'gradesDistribution' : IDL.Record({
    'a' : IDL.Nat,
    'b' : IDL.Nat,
    'c' : IDL.Nat,
    'd' : IDL.Nat,
    'f' : IDL.Nat,
  }),
  'totalRecords' : IDL.Nat,
  'averageScore' : IDL.Float64,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllRecords' : IDL.Func([], [IDL.Vec(RawRecord)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMyRecords' : IDL.Func([], [IDL.Vec(RawRecord)], ['query']),
  'getStats' : IDL.Func([], [Stats], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitPrediction' : IDL.Func(
      [
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Text,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const RawRecord = IDL.Record({
    'extracurriculars' : IDL.Nat,
    'studentName' : IDL.Text,
    'owner' : IDL.Principal,
    'predictedScore' : IDL.Nat,
    'predictedGrade' : IDL.Text,
    'studyHours' : IDL.Nat,
    'assignmentsCompleted' : IDL.Nat,
    'attendance' : IDL.Nat,
    'timestamp' : IDL.Int,
    'previousGPA' : IDL.Nat,
    'sleepHours' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Stats = IDL.Record({
    'gradesDistribution' : IDL.Record({
      'a' : IDL.Nat,
      'b' : IDL.Nat,
      'c' : IDL.Nat,
      'd' : IDL.Nat,
      'f' : IDL.Nat,
    }),
    'totalRecords' : IDL.Nat,
    'averageScore' : IDL.Float64,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllRecords' : IDL.Func([], [IDL.Vec(RawRecord)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMyRecords' : IDL.Func([], [IDL.Vec(RawRecord)], ['query']),
    'getStats' : IDL.Func([], [Stats], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitPrediction' : IDL.Func(
        [
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Text,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };