/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface RawRecord {
  'extracurriculars' : bigint,
  'studentName' : string,
  'owner' : Principal,
  'predictedScore' : bigint,
  'predictedGrade' : string,
  'studyHours' : bigint,
  'assignmentsCompleted' : bigint,
  'attendance' : bigint,
  'timestamp' : bigint,
  'previousGPA' : bigint,
  'sleepHours' : bigint,
}
export interface Stats {
  'gradesDistribution' : {
    'a' : bigint,
    'b' : bigint,
    'c' : bigint,
    'd' : bigint,
    'f' : bigint,
  },
  'totalRecords' : bigint,
  'averageScore' : number,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllRecords' : ActorMethod<[], Array<RawRecord>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMyRecords' : ActorMethod<[], Array<RawRecord>>,
  'getStats' : ActorMethod<[], Stats>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitPrediction' : ActorMethod<
    [number, number, number, number, number, number, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];